# Generated by Django 5.1.7 on 2025-03-30 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_orden_ordenitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='archivo_audio',
        ),
    ]
